### ISSUE TITLE
Request: Ability to disable output

### ISSUE THREAD

**Issue by e4lam** [martinus/nanobench#15]
Perhaps there's already a way? But I couldn't find how to disable the output altogether. The use case is to be able to keep benchmarking with different data sizes so that one can programmatically determine algorithm thresholds using nanobench.

**Comment by martinus** [comment]
I have just added a `output()` method to config, there you can specify an outstream, e.g. with `cfg.output(&std::cerr)`, or disable output with `cfg.output(nullptr)`.

No release yet though, you'll have to use the latest nanobench.h: https://github.com/martinus/nanobench/blob/master/src/include/nanobench.h

**Comment by e4lam** [comment]
Thank you!
