### ISSUE TITLE
comparisons of results

### ISSUE THREAD

**Issue by martinus** [martinus/nanobench#18]
Ability to store and later compare results. Maybe multiple results, to create a graph with changes over time

Some statistical analysis would be nice. Maybe output in a format that's understood by some good tool

**Comment by jfalcou** [comment]
My 2cts on this as I have quite the same need.
Csv is OK for processing with excel but maybe a format compatible with scipy or R could be good.

**Comment by martinus** [comment]
Do you have any good example for R or scipy? I don't use these. I'll probably add a template for pyperf json, which allows more analysis and comparison. The format is a bit limited though, mostly because it can only hold a single benchmark result.

**Comment by martinus** [comment]
I've now added pyperf support, which is described here: https://nanobench.ankerl.com/tutorial.html#pyperf-python-pyperf-module-output

**Comment by alexeyr** [comment]
I was planning to ask for custom statistics, but I think this already covers all of those I would want :)
