### ISSUE TITLE
API of latest release (v3.1.0) doesn't match tutorial / README

### ISSUE THREAD

**Issue by chohner** [martinus/nanobench#31]
The latest `v3.1.0 ` release does not match any of the examples since changing `Config` to `Bench`. This is quite a big (currently) undocumented API break and potentially warrants a new release?

**Comment by andersfylling** [comment]
I'm struggling with this too.

**Comment by martinus** [comment]
Unfortunately the documentation is out of date. The coming release 4.0 is quite a big refactoring which has changed a lot of the API, and I'll have to update most of the documentation for that.

**Comment by martinus** [comment]
You can find the most recent nanobench documentation here: https://nanobench.ankerl.com/

- [ ] Describe & update templating
- [ ] source comments: `Result`
- [ ] source comments: `doNotOptimizeAway`
- [ ] source comments: `BigO`
- [ ] source comments: `templates` namespace

For 4.1.0: 
- [ ] document Internals (how autoscaling works, PerformanceCounters tuning)
- [ ] benchmark & speed up compilation

**Comment by martinus** [comment]
Huge update to the documentation, I consider this finished for 4.0.0.
