### ISSUE TITLE
Suggestions for benchmarking parallel data structures?

### ISSUE THREAD

**Issue by e4lam** [martinus/nanobench#33]
Hi, I want to do some microbenchmarking of parallel data structures where I run a bunch of parallel tasks and then time the work that they do in different threads. The problem is that I want to combine the timings somehow of the work done in each task to avoid including the overhead of the task scheduler. Any suggestions for using nanobench for this usage scenario? Thanks!

**Comment by martinus** [comment]
nanobench works by iteratively doing the same thing multiple times and measure that, I don't think that's really possible with what you describe. I think your best bet is to just start and stop a chrono timer in each thread, stop them where appropriate, and sum up all the times.

**Comment by e4lam** [comment]
Ok, thanks!
