### ISSUE TITLE
the cycles/value output doesn't show on some platform

### ISSUE THREAD

**Issue by jfalcou** [martinus/nanobench#36]
Hi,

I'm using nanobench in some of my projects, everything's good.
Some question though. On one of my linux system using arch-linux, I got all the cycles/value, IPC, branch etc measures displayed.
One of my coworker use Linux Mint ubuntu 18.04 and he got non of those.

Is there a specific package to install so that the extra perf counter get picked up ?

**Comment by Lectem** [comment]
I had the same issue on a Debian based system, it is a matter of access
rights.
You can change those using ACL or changing perf_event paranoid. See
https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html#id30

Le dim. 28 juin 2020 à 18:34, Joel Falcou <notifications@github.com> a
écrit :

**Comment by martinus** [comment]
Ah, that's good to know. I also use arch linux and it always works out of the box.

**Comment by jfalcou** [comment]
+1 for arch linux :+1: 
Maybe a small section in the doc pointing this out would be good ?

**Comment by martinus** [comment]
Done, I've added a note at the top of the tutorial: https://nanobench.ankerl.com/tutorial.html
