### ISSUE TITLE
Why a fork on pyperf?

### ISSUE THREAD

**Issue by elichai** [martinus/nanobench#38]
Hi,
Is there a reason why does it recommend a fork of pyperf (https://github.com/vstinner/pyperf) instead of pyperf itself? (https://github.com/psf/pyperf)

Thanks!

**Comment by martinus** [comment]
Hi, no reason at all! It seems to me that vstinner/pyperf was the original implementation and has just recently been moved to psf/pyperf: https://github.com/psf/pyperf/commit/3949da74ebbe57291cb6d0d4bf6db6130cb4cc04

**Comment by martinus** [comment]
I'll update the link

**Comment by elichai** [comment]
> Hi, no reason at all! It seems to me that vstinner/pyperf was the original implementation and has just recently been moved to psf/pyperf: [psf/pyperf@3949da7](https://github.com/psf/pyperf/commit/3949da74ebbe57291cb6d0d4bf6db6130cb4cc04)

Oh I did not know that, cool that they adapted it :)
