### ISSUE TITLE
Option to suppress unstable warnings at run-time?

### ISSUE THREAD

**Issue by tueda** [martinus/nanobench#39]
Though it is a good thing to show warnings for unstable results (`:wavy_dash: ... (Unstable with ...`), sometimes one wants to run benchmarks in an environment where the execution is potentially perturbed by other processes and so results are known to be unstable; for example, in continuous integration.

So, it might be handy if an environment variable (`NANOBENCH_NO_UNSTABLE_WARNING` or something) could change the behaviour and suppress warnings for unstable results.

Changing the behaviour by a command-line option could be an alternative way, but I think an environment variable is more suitable for CI, and I guess it is easier to implement.

**Comment by martinus** [comment]
Sounds like a good idea. I think I'll add an environment variable `NANOBENCH_SUPPRESS_WARNINGS` to so this and also suppress the other warnings like for frequency scaling

**Comment by martinus** [comment]
Fixed in https://github.com/martinus/nanobench/commit/dd25c032eb06ed5fa1408a868fa6cb46a439a624, see https://nanobench.ankerl.com/reference.html#nanobench-suppress-warnings-no-stability-warnings

**Comment by tueda** [comment]
It perfectly works. Thanks!
