### ISSUE TITLE
Clarify use of doctest in documentation?

### ISSUE THREAD

**Issue by alexeyr** [martinus/nanobench#40]
The documentation says

> In the remaining examples, I’m using doctest as a unit test framework, which is like Catch2 - but compiles much faster. It pairs well with nanobench.

The benefits I can see from it is benchmark registration and filtering; is there anything else? And it may be useful to explicitly mention/show how it allows filtering. 

On the other hand, you get the test results table which isn't too useful because they definitely should all pass. It can be suppressed by using
```
int main(int argc, char** argv) {
    doctest::Context context;
    context.setOption("out", "/dev/null");
    context.setOption("no-version", true);
    context.applyCommandLine(argc, argv);
    return context.run();
}
```
which may also be worth mentioning.

**Comment by martinus** [comment]
Not much else, I just wanted to note nanobench is made to be used with other test frameworks. I've update the wording a bit. Thanks for the snippet though!
