### ISSUE TITLE
Option to show seconds or milliseconds per op instead of nanoseconds

### ISSUE THREAD

**Issue by alexeyr** [martinus/nanobench#41]
For some benchmarks nanoseconds are too small a time unit. On the other hand, it isn't like their use is likely to actually hurt, so this may not provide enough benefit.

**Comment by martinus** [comment]
shouldn't be difficult to add, I'll have a look

**Comment by martinus** [comment]
I've added a configuration `timeUnit` to do this, see here: https://nanobench.ankerl.com/reference.html#_CPPv4N6ankerl9nanobench5Bench8timeUnitERKNSt6chrono8durationIdEERKNSt6stringE
