### ISSUE TITLE
CMake integration (interface library)

### ISSUE THREAD

**Issue by tueda** [martinus/nanobench#42]
There is a `CMakeLists.txt` in the nanobench repository, but it seems for development and not for users of the library. It would be nice if nanobench could be integrated in a project via CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) or as a Git submodule (if one can't use relatively new versions of CMake). Specifically, the following `CMakeLists.txt` should work:

```cmake
cmake_minimum_required(VERSION 3.14)

project(
  CMakeNanobenchExample
  VERSION 1.0
  LANGUAGES CXX)

include(FetchContent)

FetchContent_Declare(
  doctest
  GIT_REPOSITORY https://github.com/onqtam/doctest.git
  GIT_TAG 2.4.0
  GIT_SHALLOW TRUE)

FetchContent_Declare(
  nanobench
  GIT_REPOSITORY https://github.com/martinus/nanobench.git
  GIT_TAG v4.0.2
  GIT_SHALLOW TRUE)

FetchContent_MakeAvailable(doctest nanobench)

add_executable(MyExample my_example.cpp)
target_link_libraries(MyExample PRIVATE doctest nanobench)
```

Basically, what [`FetchContent_MakeAvailable`](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_makeavailable) does here is cloning repositories declared by [`FetchContent_Declare`](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_declare) and then including them  via `add_subdirectory`.

The problems are:
1. nanobench is not an [interface library](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#interface-libraries). It should be easy to create a header-only library with CMake's interface library feature, for example, see [here](http://mariobadr.com/creating-a-header-only-library-with-cmake.html).
2. `CMakeLists.txt` in the nanobench repository performs many things, searching ccache and including subdirectories for testings, which are not relevant for library users. Especially, it leads to building many test programs. To avoid this, perhaps looking into `CMakeLists.txt` of [doctest](https://github.com/onqtam/doctest/blob/master/CMakeLists.txt) or [Catch2](https://github.com/catchorg/Catch2/blob/master/CMakeLists.txt) is helpful, where they detect whether or not the libraries are included as a subdirectory. See also [here](https://gitlab.com/CLIUtils/modern-cmake/-/blob/master/examples/extended-project/CMakeLists.txt), which is an example in [this site](https://cliutils.gitlab.io/modern-cmake/).

**Comment by martinus** [comment]
Thanks for the detailed writeup! I think I've managed to make this possible now, the example should work with release v4.1.0. I've also updated the documentation: https://nanobench.ankerl.com/tutorial.html#cmake-integration
