### ISSUE TITLE
Manual Timing

### ISSUE THREAD

**Issue by abduld** [martinus/nanobench#45]
Is there a mechanism (similar to google benchmark) to perform manual timing. I.e. not use the clock builtin to nanbench but provide our own iteration time to nanobench.

**Comment by martinus** [comment]
No, currently that's not possible. On startup nanobench internally tunes itself to the accuracy of the `std::chrono::steady_clock`, and that wouldn't be easily possible with a customizable clock. Why do you think this is necessary?

**Comment by abduld** [comment]
I'd like to benchmark some GPU code and that needs to use more accurate timers provided by the cuda / opencl apis

**Comment by martinus** [comment]
Sorry currently I don't have much time to work on this. I'll keep the ticket open, but don't expect anything soon
