### ISSUE TITLE
which one is more important, ns/op or total?

### ISSUE THREAD

**Issue by feng-y** [martinus/nanobench#46]
|               ns/op |                op/s |    err% |          ins/op |          cyc/op |    IPC |         bra/op |   miss% |     total | benchmark
|--------------------:|--------------------:|--------:|----------------:|----------------:|-------:|---------------:|--------:|----------:|:----------
|        7,266,190.00 |              137.62 |    3.3% |    4,721,603.00 |   15,556,024.00 |  0.304 |   1,302,758.00 |   13.0% |      0.18 | `hopscotch_map`
|       35,033,938.00 |               28.54 |    0.9% |    4,961,470.00 |   76,638,408.00 |  0.065 |   1,097,837.00 |   23.8% |      0.44 | `unordered_map`
|        **6,696,755.00** |              149.33 |    1.7% |    8,040,577.00 |   14,634,752.00 |  0.549 |     767,069.00 |   17.1% |      **0.12** | `flat_hash_map`
|        **7,676,762.00** |              130.26 |    2.3% |    7,126,320.00 |   16,794,536.00 |  0.424 |     774,163.00 |   17.6% |      **0.09** | `F14FastMap`

flat_hash_map： ns/op :  6,696,755.00, total : 0.12
F14FastMap: ns/op: 7,676,762.00, total: 0.09

**Comment by martinus** [comment]
`ns/op` shows the runtime performance, and usually is the most important.

`total` only shows how long the test took, e.g. if you get a very large number here you might want to change the benchmark code, so that it doesn't take so long.

**Comment by martinus** [comment]
PS: have a look at this hashmap: https://github.com/martinus/robin-hood-hashing
