### ISSUE TITLE
how to deal with unstable results?

### ISSUE THREAD

**Issue by feverzsj** [martinus/nanobench#49]
I'm benchmarking protobuf. There are always some warning on unstable result on first run, even after increasing the warmup and minimum iteration:

```
TEST_CASE("varint encode benchmark"){

    nanobench::Bench b;
    b.title("varint encode")
        .warmup(100000)
        .relative(true);
    b.performanceCounters(true);

    uint8_t buf[10] = {};

    b.minEpochIterations(10000000).run("google uint32_t", [&]{
        nanobench::doNotOptimizeAway(
            google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(static_cast<uint32_t>(2961488830), buf));
    });

    b.minEpochIterations(10000000).run("google uint64_t", [&]{
        nanobench::doNotOptimizeAway(
            google::protobuf::io::CodedOutputStream::WriteVarint64ToArray(static_cast<uint64_t>(-41256202580718336), buf));
    });

//     std::ofstream f{"varint encode benchmark.html"};
//     b.render(nanobench::templates::htmlBoxplot(), f);

} // TEST_CASE("varint encode benchmark")


TEST_CASE("varint decode benchmark"){

    nanobench::Bench b;
    b.title("varint decode")
        .warmup(100000)
        .relative(true);
    b.performanceCounters(true);

    std::initializer_list<uint8_t> buf32 = {0xbe, 0xf7, 0x92, 0x84, 0x0b};
    std::initializer_list<uint8_t> buf64 = {0x9b, 0xa8, 0xf9, 0xc2, 0xbb, 0xd6, 0x80, 0x85, 0xa6, 0x01};

    b.minEpochIterations(10000000).run("google uint32_t", [&]{
        uint32_t v;
        nanobench::doNotOptimizeAway(
            google::protobuf::io::CodedInputStream{buf32.begin(), (int)buf32.size()}.ReadVarint32(&v));
    });

    b.minEpochIterations(10000000).run("google uint64_t", [&]{
        uint64_t v;
        nanobench::doNotOptimizeAway(
            google::protobuf::io::CodedInputStream{buf64.begin(), (int)buf64.size()}.ReadVarint64(&v));
    });

//     std::ofstream f{"varint decode benchmark.html"};
//     b.render(nanobench::templates::htmlBoxplot(), f);

} // TEST_CASE("varint decode benchmark")
```

encode results for 3 runs:

| relative |               ns/op |                op/s |    err% |     total | varint encode
|---------:|--------------------:|--------------------:|--------:|----------:|:--------------
|   100.0% |                6.95 |      143,943,329.37 |    5.3% |      0.87 | :wavy_dash: `google uint32_t` (Unstable with ~11,003,388.7 iters. Increase `minEpochIterations` to e.g. 110033887)
|    54.0% |               12.86 |       77,751,471.35 |    2.0% |      1.56 | `google uint64_t`

| relative |               ns/op |                op/s |    err% |     total | varint encode
|---------:|--------------------:|--------------------:|--------:|----------:|:--------------
|   100.0% |                7.26 |      137,743,666.50 |    4.8% |      0.88 | `google uint32_t`
|    55.0% |               13.21 |       75,702,505.04 |    1.6% |      1.62 | `google uint64_t`

| relative |               ns/op |                op/s |    err% |     total | varint encode
|---------:|--------------------:|--------------------:|--------:|----------:|:--------------
|   100.0% |                7.22 |      138,464,875.81 |    2.9% |      0.86 | `google uint32_t`
|    56.4% |               12.80 |       78,102,820.79 |    1.9% |      1.55 | `google uint64_t`

decode results for 3 runs:

| relative |               ns/op |                op/s |    err% |     total | varint decode
|---------:|--------------------:|--------------------:|--------:|----------:|:--------------
|   100.0% |               26.93 |       37,132,748.98 |    1.9% |      3.26 | `google uint32_t`
|   101.0% |               26.67 |       37,490,487.35 |    3.4% |      3.23 | `google uint64_t`

| relative |               ns/op |                op/s |    err% |     total | varint decode
|---------:|--------------------:|--------------------:|--------:|----------:|:--------------
|   100.0% |               26.64 |       37,543,305.23 |    1.4% |      3.23 | `google uint32_t`
|   102.7% |               25.93 |       38,558,548.08 |    1.2% |      3.17 | `google uint64_t`

| relative |               ns/op |                op/s |    err% |     total | varint decode
|---------:|--------------------:|--------------------:|--------:|----------:|:--------------
|   100.0% |               27.45 |       36,434,999.13 |    0.8% |      3.31 | `google uint32_t`
|   103.1% |               26.62 |       37,568,188.30 |    2.8% |      3.23 | `google uint64_t`

compiled with vs2019 16.8 msvc /O2
runs on Win10, i3-3220@3.3GHz

**Comment by Lectem** [comment]
Hi, there are many things that can make benchmarks unstable, and it does not necessarily comes from the benchmarking code.
I see that you are running the code on windows, which means you probably have turbo boost enabled and CPU dynamic frequency enabled too.

I do not have a link to a tool that stabilizes everything on windows, but here is a (relatively small) list of what can impact the stability of your benchmarks: https://doc.calcite.siliceum.com/performance/stability/index.html

Increasing the number of iterations will most likely not help here. 5.3% is actually not that much of a deviation for a non-tuned system, especially taking into account CPU issues such as the Intel JCC Erratum ( https://www.intel.com/content/dam/support/us/en/documents/processors/mitigations-jump-conditional-code-erratum.pdf ).

My best advice here is to look for a way to stabilize your system on windows, or switch to linux for benchmarking.

I also recommand the following book which is a great resource https://book.easyperf.net/perf_book .

**Comment by feverzsj** [comment]
@Lectem thanks for your recommendation. I'll have a good read on them.

**Comment by martinus** [comment]
I'd say the most important thing for stable results is to make sure the CPU is locked to a certain frequency. No turbo mode, no frequency scaling. That's easy to do on linux with pyperf, but I don't know how to do this on Windows. Of course, the system should be otherwise relatively idle. No websurfing or youtube videos in the background.
