### ISSUE TITLE
Clarify err%

### ISSUE THREAD

**Issue by mcandre** [martinus/nanobench#54]
What does the `err%` metric measure? I check my application with unit tests, libFuzzer, and many clang flags. I would expect this value to be zero, but it is reporting about 5% error rate.

Does `err%` indicate that nanobench observes an iteration crashing? Could you please expand the documentation for what this metric means?

**Comment by martinus** [comment]
nanobench evaluates each benchmark multiple times, and ideally each measurement produces exactly the same runtime. If the runtime fluctuates for some reason (e.g. unstable environment, or different CPU cache lines are hot), then you get a higher `err%`. Usually high err% means your results might not be accurate for whatever reason
