### ISSUE TITLE
compare with other frameworks

### ISSUE THREAD

**Issue by martinus** [martinus/nanobench#7]
Run app 100 times, show nice diagram with the accuracy

**Comment by onqtam** [comment]
Hi Martin,
I'm so glad you've shown how this works together with doctest!

I just wanted to link to another similar benchmarking library: https://github.com/iboB/picobench

**Comment by martinus** [comment]
Hi Victor, thanks for doctest! I'm using it in all my open source projects.

I've now added a comparison with picobench too, I didn't know about that library
