### ISSUE TITLE
Add CMake options to disable building tests and examples

### ISSUE THREAD

**Issue by tocic** [martinus/nanobench#73]
When building the library using

```
cmake -B build/ -S .
cmake --build build/
```

examples and tests are also built. Is it possible to add CMake options for disabling that (see, e.g., [google benchmark](https://github.com/google/benchmark/blob/49aa374da96199d64fd3de9673b6f405bbc3de3e/CMakeLists.txt#L334))? It's useful for [packaging](https://aur.archlinux.org/packages/nanobench).

**Comment by martinus** [comment]
I'm bad with cmake, if you are still interested could you do a PR?

**Comment by tocic** [comment]
Actually, I found out that thanks to #60 you can avoid building tests and examples via building only the `nanobench` target:

```shell
cmake --build "build/" --target "nanobench"
```

It will not eliminate the configuration step for other targets, but that's not critical. Also, it'd be nice to be able to create dynamic and header-only versions of the library with `CMake`, but those are separate issues.
