### ISSUE TITLE
truncation warning in 4.3.8

### ISSUE THREAD

**Issue by Philippe91** [martinus/nanobench#80]
With the new 4.3.8, there is a truncation warning (warning == error for me). This warning happens when the container has a 32 bit range (eg. Qt5 vector).

This is in Rng::shuffle:

`        auto b1 = static_cast<size_t>`

suggested fix:

`        auto b1 = static_cast<decltype(i)>`

Same thing for b2 = ....

**Comment by martinus** [comment]
Can you

**Comment by martinus** [comment]
thanks!
