### ISSUE TITLE
setup support

### ISSUE THREAD

**Issue by screwzm** [martinus/nanobench#81]
I am wondering whether superb nanobench supports setup that is not part of the benchmar? For my cases, I would like to setup some context before running the actual part that needs to be benchmarked.

Basically I am looking for something like this:

int main() {

    ankerl::nanobench::Bench().run("some double ops", [&] {
       // stop timing
       setup()
       // resume timing

      actual_code_to_banchmark_based_on_the_setup();
        
    });
}

**Comment by screwzm** [comment]
Google benchmark is bad since the state.PauseTiming/ResumeTiming have heavy overhead themselves, hence cuase the result not usable.

**Comment by martinus** [comment]
no because this can't be done well. Create two benchmarks: one with setup, another one with setup & actual benchmark code, and subtract the first.

**Comment by martinus** [comment]
Closed in favor of #86
