### ISSUE TITLE
Remove dangling 'compile_commands.json' symlink

### ISSUE THREAD

**Issue by helmesjo** [martinus/nanobench#88]
I'm [currently packaging](https://github.com/build2-packaging/nanobench) `nanobench` for `build2`, but I've run into a problem with the dangling [`compile_commands.json`](https://github.com/martinus/nanobench/blob/407feab7adebc5ddf663200c72468e24dd2cf139/compile_commands.json) symlink since `build2` does not tolerate this (or more specifically, the `git` commands with specific optimization flags that `build2` executes).

Could this file be removed, or a dummy-one created in `build/compile_commands.json` (which should just be overwritten when it's generated)?

Thanks!

**Comment by martinus** [comment]
Hi, that can be removed, is just there to help my ide. I'll remove it

**Comment by helmesjo** [comment]
@martinus Great! Could there also be a patch-release done? I'd like to preferably target a specific tag for the package.

**Comment by martinus** [comment]
I'll create a new version this weekend

**Comment by martinus** [comment]
kids are asleep so I could do it now :smile: 
Released v4.3.11
