### ISSUE TITLE
How to see more info in the output?

### ISSUE THREAD

**Issue by Zabrane** [martinus/nanobench#99]
Hi @martinus 

First of all, thanks for `nanobench`. 
When trying the example in the doc on both `Linux/macOS` with `nanobench v4.3.11`, i got this:
```
$ ./full_example
|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|                7.65 |      130,673,512.18 |    0.8% |      0.01 | `compare_exchange_strong`
```

But the [doc](https://nanobench.ankerl.com/tutorial.html#usage) shows a different output format with additional columns:
```
|               ns/op |                op/s |    err% |          ins/op |          cyc/op |    IPC |         bra/op |   miss% |     total | benchmark
|--------------------:|--------------------:|--------:|----------------:|----------------:|-------:|---------------:|--------:|----------:|:----------
|                5.63 |      177,595,338.98 |    0.0% |            3.00 |           17.98 |  0.167 |           1.00 |    0.1% |      0.00 | `compare_exchange_strong`
```

What should I do to get these extra columns (ex. `ins/op`, `cyc/op` ...)?
Help appreciated.

**Comment by helmesjo** [comment]
See [the docs](https://nanobench.ankerl.com/tutorial.html#usage), specifically this piece:

![image](https://github.com/martinus/nanobench/assets/2501070/ed378885-4ed3-4761-bd5a-837353487bb2)

**Comment by martinus** [comment]
Exactly, unfortunately additional hardware information is only available on Linux.

**Comment by Zabrane** [comment]
Thanks guys. Running the same example with `sudo` on `Linux` gave me the extra `perf's` columns
